# Generated by Django 4.2 on 2023-06-23 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abi',
        ),
    ]
